### PR TITLE
DOC-2165-BE-GKE-Rolls-Tab-Support-Missing-Statuses-Roll-scope-Parameters 

### PR DESCRIPTION
**Pull request by AvishagK**
_This is the default pull request template. You can customize it by adding a `pull_request_template.md` at the root of your repo or inside the `.github` folder._

# Jira Ticket
https://spotinst.atlassian.net/browse/DOC-2165

_Include a link to your Jira Ticket_
_Example: [JIRAISS-1234](https://spotinst.atlassian.net/browse/JIRAISS-1234)_

# Demo

_Please add a recording of the feature/bug fix in work. if you added new routes, the recording should show the request and response for each new/changed route_

# Checklist:
- [ ] I have filled relevant self assessment ([NodeJS](https://docs.google.com/forms/d/e/1FAIpQLSfl14u9AOBAmxVJ272tvO7XNuXE-EMvWaGcaRZalu1UAKB7RA/viewform), [Frontend](https://docs.google.com/forms/d/e/1FAIpQLSdiBPNKH81w_EkavihVL8Uwb0j7tP8PwJmLFYm2nCOQxz-1qw/viewform), [Backend](https://docs.google.com/forms/d/e/1FAIpQLSed_PsTJ5-XIWkFL6BSDE2AQRBVPmwc3PAmHZkUn-erzVI37Q/viewform?usp=sf_link))
- [ ] I have run ESlint on my changes and fixed all warnings and errors (**NodeJS & Frontend Services**)
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have validated all the requirements in the Jira task were answered
- [ ] I have all neccessary approvals for the design/mini design of this task
- [ ] I have approved the API changes and granular permission patterns (documentation subtask) (**For public services only**)

### CODE REVIEW

**Review by rickshar — CHANGES_REQUESTED** [review]
@AvishagK 
Change: line 36: Add a breif description or comment about the roll. The comment should be limited to 256 chars.
To
Add a short comment about the roll (up to 256 chars).
Change: Line 44:  During the roll, if the parameter is set to true we honor PDB during the instance replacement.
To:
During the roll, if the parameter is set to 'true', PDB is honored during the instance replacement.
Change:line 48:
To:  Indicates the threshold percentage of minimum healthy instances in a single batch. 
 If the number is below the threshold, the cluster roll will fail. 
 The parameter value has a range of 1-100 (default = 50%).

**Review by rickshar — CHANGES_REQUESTED** [review]
Change:Line 6:
To"
   When set to 'True' and virtual node group identifiers are defined to roll, 
    the specified virtual node group(s) will be blocked from scaling up. 
    Replacements will scale up in other virtual node groups that match the displaced pods instead. This applies to migrating nodes from one virtual node group to another.

**Review by rickshar — CHANGES_REQUESTED** [review]
Line 6:
To:
Value is a percentage to set the size of a batch in a roll. Valid values are 0-100.

**Review by yinnonbar — DISMISSED** [review]

**Comment by AvishagK** [comment]
> Change:Line 6: To" When set to 'True' and virtual node group identifiers are defined to roll, the specified virtual node group(s) will be blocked from scaling up. Replacements will scale up in other virtual node groups that match the displaced pods instead. This applies to migrating nodes from one virtual node group to another.


Hi,
please specify the string you want to change from to?
@rickshar

**Comment by AvishagK** [comment]
> Line 6: To: Value is a percentage to set the size of a batch in a roll. Valid values are 0-100.

Hi,
please specify the string you want to change from to?
@rickshar

**Review by yinnonbar — APPROVED** [review]

**Pull request closed without merging**
